name: Test running setup-licensed-dev
permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  # run on demand
  workflow_dispatch:

jobs:
  gem:
    runs-on: ubuntu-latest

    steps:
      # checkout the repo
      - uses: actions/checkout@v7

      # install ruby
      - uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073
        with:
          bundler-cache: 'true'
          ruby-version: "3.0"

      # install node
      - uses: actions/setup-node@v7
        with:
          node-version: "24.x"

      # run the action
      - name: Run setup-licensed-dev
        uses: ./
        with:
          version: '4.x'

  exe:
    runs-on: ubuntu-latest

    steps:
      # checkout the repo
      - uses: actions/checkout@v7

      # do not install ruby

      # install node
      - uses: actions/setup-node@v7
        with:
          node-version: "24.x"

      # run the action
      - name: Run setup-licensed-dev
        uses: ./
        with:
          version: '3.x'
